
#ifndef __FTN_CMD__H_
#define __FTN_CMD__H_

enum FTN_CMD_TYPE {
	FTN_CLIENT_HB = 0,
	FTN_CLIENT_GET_RANDOM,
	FTN_CLIENT_LOGIN,
	FTN_BROADCAST_NEW_MACHINE,
	FTN_CS_LOGIN_FCS,
	FTN_ASK_SYNC_DIR,
	FTN_SYNC_TO_CS_ASK,
	FTN_SYNC_FILE_TO_CS,
	FTN_NOTIFY_FOSS_OPER,
	FTN_SERVER_PUT_ERR_PROTOCOL,
	FTN_CLIENT_ERR_REQ
};

extern const char *ftn_cmd_str[FTN_CLIENT_ERR_REQ];

enum KSHOW_PROTOCL_ERRTYPE {
	FTN_PROTOCL_OK = 0,
	FTN_PROTOCL_ERR_BODY_LEN,
	FTN_PROTOCL_ERR_OPTION,
	FTN_PROTOCL_ERR_USER_LOGIN,
	FTN_PROTOCL_ERR_UNDEF,
	FTN_PROTOCL_ERRTYPE_MAX
};

extern const char *ftn_protocol_errmsg[FTN_PROTOCL_ERRTYPE_MAX];

enum {
	S_TYPE_KSHOW_CLIENT = 0,
	S_TYPE_KSHOW_ACCESS_PEER,
	S_TYPE_KSHOW_GET_FD_BY_UID
};

#endif
